[package]
name = "ffmpeg-rs-raw"
version = "0.1.0"
edition = "2021"
repository = "https://git.v0l.io/Kieran/ffmpeg-rs-raw.git"
authors = ["Kieran"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
anyhow = "1.0.91"
ffmpeg-sys-the-third = { git = "https://git.v0l.io/Kieran/ffmpeg-the-third.git", rev = "e5f8e077b04b10d5887bce4df1eb1a71738a6c66", package = "ffmpeg-sys-the-third" }
libc = { version = "0.2.160" }
slimbox = "0.1.0"
log = "0.4.22"

[dev-dependencies]
env_logger = "0.11.5"
